export let haikus = [
  {
    author: "Walt Whitman",
    id: 0.7094449303806339,
    line1: " clouds of the west---sun",
    line2: " there half an hour high---i see you",
    line3: " also face to face.",
    status: "keep",
    title: "Crossing Brooklyn Ferry",
    url: "http://www.poetryfoundation.org/poem/174738",
  },
  {
    author: "Heather McHugh",
    id: 0.5448020600936119,
    line1: " around a log or snag",
    line2: " the surface currents run like",
    line3: " lumber about a knot.",
    status: "keep",
    title: "Constructive",
    url: "http://www.poetryfoundation.org/poem/172078",
  },
  {
    author: "Lynn Crosbie",
    id: 0.511393412696047,
    line1: " i think of sewing him",
    line2: " a pole-bag, with cobra skin",
    line3: " and vegetable powder.",
    status: "keep",
    title: "True Confessions Variations",
    url: "http://www.poetryfoundation.org/poem/175490",
  },
  {
    author: "J. P. White",
    id: 0.6821184775651621,
    line1: " between us and them",
    line2: " stands the great wound, swallowing",
    line3: " all tears, all voices.",
    status: "keep",
    title: "Thinking About the Enemy",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/30788",
  },
  {
    author: "Spencer Reece",
    id: 0.02806445630464749,
    line1: " the horizon's flashing",
    line2: " fastens tight, sealing the blue",
    line3: " hills with vermilion.",
    status: "keep",
    title: "At Thomas Merton's Grave",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/237490",
  },
  {
    author: "R. S. Thomas",
    id: 0.7325520134174862,
    line1: " in the spring of the",
    line2: " year the wind brought the news of",
    line3: " a woman's beauty.",
    status: "keep",
    title: "Perspectives",
    url: "http://www.poetryfoundation.org/poem/237210",
  },
  {
    author: "Joyce Sidman",
    id: 0.8927216142989024,
    line1: " nose tucked under tail,",
    line2: " you are a warm, furred planet",
    line3: " centered in my bed.",
    status: "keep",
    title: "Dog in Bed",
    url: "http://www.poetryfoundation.org/poem/246132",
  },
  {
    author: "Howard Nemerov",
    id: 0.4786447266727142,
    line1: " before you can learn",
    line2: " the trees, you have to learn the",
    line3: " language of the trees.",
    status: "keep",
    title: "Learning the Trees",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/22392",
  },
  {
    author: "Marianne Boruch",
    id: 0.5785053210721077,
    line1: " all along the town touched",
    line2: " a river, the river the",
    line3: " filth falling through it.",
    status: "keep",
    title: "He was touched or he touched or",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/182820",
  },
  {
    author: "Lynn Crosbie",
    id: 0.5541674958695434,
    line1: " small glider, his veined",
    line2: " wings are sheer parasols, gauzy skirts",
    line3: " that admit the light.",
    status: "keep",
    title: "The Fly",
    url: "http://www.poetryfoundation.org/poem/175485",
  },
  {
    author: "Maxine W. Kumin",
    id: 0.23299266257766138,
    line1: " in winter we lure",
    line2: " the birds with suet, thaw lungs and",
    line3: " kidneys for the cat.",
    status: "keep",
    title: "Family Reunion",
    url: "http://www.poetryfoundation.org/poem/178811",
  },
  {
    author: "Chana Bloch",
    id: 0.6645423316628786,
    line1: " i bend down, taste the",
    line2: " fluted nipples, the elbows,",
    line3: " the pads of the feet.",
    status: "keep",
    title: "Eating Babies",
    url: "http://www.poetryfoundation.org/poem/245482",
  },
  {
    author: "Dan Beachy-Quick",
    id: 0.9297739138986898,
    line1: " leaning back in the",
    line2: " tall grass, putting my book aside, my",
    line3: " toe covers the sun.",
    status: "keep",
    title: "Museums",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/237456",
  },
  {
    author: "Yusef Komunyakaa",
    id: 0.22789207195285388,
    line1: " a hard wind raps at",
    line2: " the door, the new year prowling",
    line3: " in a black overcoat.",
    status: "keep",
    title: "After Summer Fell Apart",
    url: "http://www.poetryfoundation.org/poem/177458",
  },
  {
    author: "Yvor Winters",
    id: 0.6593429676883581,
    line1: " beyond the river,",
    line2: " gray volcanic stone in rolling hills:",
    line3: " the river moved alone.",
    status: "keep",
    title: "The Journey",
    url: "http://www.poetryfoundation.org/poem/177276",
  },
  {
    author: "Paisley Rekdal",
    id: 0.39448705369419734,
    line1: " these days what else to",
    line2: " do but leer at any boy with",
    line3: " just the right hairline.",
    status: "keep",
    title: "Dear Lacuna, Dear Lard:",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/146796",
  },
  {
    author: "Lew Welch",
    id: 0.7709057528403934,
    line1: " standing in the boat",
    line2: " one night i watched the lake go",
    line3: " absolutely flat.",
    status: "keep",
    title: "Chicago Poem",
    url: "http://www.poetryfoundation.org/poem/244550",
  },
  {
    author: "Tracy K. Smith",
    id: 0.6594632029505404,
    line1: " what must be voices",
    line2: " bob up, then drop, like metal",
    line3: " shavings in molasses.",
    status: "keep",
    title: "The Universe: Original Motion Picture Soundtrack",
    url: "http://www.poetryfoundation.org/poem/243876",
  },
  {
    author: "Eamon Grennan",
    id: 0.9290106534787941,
    line1: " the hills a witch's quilt",
    line2: " of goldrust, flushed cinnamon,",
    line3: " wine fever, hectic lemon.",
    status: "keep",
    title: "Incident",
    url: "http://www.poetryfoundation.org/poem/175700",
  },
  {
    author: "Gregory Orr",
    id: 0.606841691508198,
    line1: " i pulled the rope of",
    line2: " braided hair and high above me",
    line3: " a bell of leaves tolled.",
    status: "keep",
    title: "Self-Portrait at Twenty",
    url: "http://www.poetryfoundation.org/poem/181539",
  },
  {
    author: "Ouyang Jianghe",
    id: 0.09983471766439533,
    line1: " few know this kind of",
    line2: " dizzy glee: an empty sky, a",
    line3: " pair of burning wings.",
    status: "keep",
    title: "The Burning Kite",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/242112",
  },
  {
    author: "Monica Youn",
    id: 0.4395273688327497,
    line1: " a gauze bandage wraps",
    line2: " the land and is unwound, stained",
    line3: " orange with sulfates.",
    status: "keep",
    title: "Ignatz Invoked",
    url: "http://www.poetryfoundation.org/poem/239386",
  },
  {
    author: "Thomas James",
    id: 0.6248845100242728,
    line1: " the moon hangs up there",
    line2: " like a stone shaken out of",
    line3: " its proper setting.",
    status: "keep",
    title: "Reasons",
    url: "http://www.poetryfoundation.org/poem/182286",
  },
  {
    author: "Hilda Morley",
    id: 0.357519278766804,
    line1: " the pavement trembles",
    line2: " with light pouring upon it",
    line3: " we are held in it.",
    status: "keep",
    title: "That Bright Grey Eye",
    url: "http://www.poetryfoundation.org/poem/247262",
  },
  {
    author: "Etheridge Knight",
    id: 0.6477628223260675,
    line1: " the night is full of",
    line2: " buggers and bastards; no moon",
    line3: " or stars light the sky.",
    status: "keep",
    title: "Apology for Apostasy?",
    url: "http://www.poetryfoundation.org/poem/181869",
  },
  {
    author: "Patricia Jabbeh Wesley",
    id: 0.8602967235290369,
    line1: " the owl, calling in",
    line2: " the setting of the sun and",
    line3: " the deer path, all erased.",
    status: "keep",
    title: "One Day",
    url: "http://www.poetryfoundation.org/poem/242222",
  },
  {
    author: "Garrett Hongo",
    id: 0.7295390733527698,
    line1: " from up the mountain,",
    line2: " the sound of obsidian,",
    line3: " flaking in the wind.",
    status: "keep",
    title: "Cruising 99",
    url: "http://www.poetryfoundation.org/poem/182014",
  },
  {
    author: "Oliver de la Paz",
    id: 0.5446319693990916,
    line1: " little urgent bells,",
    line2: " the birds steal from each other's",
    line3: " mouths which makes you hurt.",
    status: "keep",
    title: "Aubade with Bread for the Sparrows",
    url: "http://www.poetryfoundation.org/poem/249338",
  },
  {
    author: "Mary Barnard",
    id: 0.23011552707502403,
    line1: " litter of bare logs",
    line2: " in the drift--- the sea has had",
    line3: " its sharp word with them.",
    status: "keep",
    title: "Shoreline",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/9911",
  },
  {
    author: "Keith Waldrop",
    id: 0.6753180987406768,
    line1: " the music of a",
    line2: " crash caught in the hollow of",
    line3: " a wooded hillside.",
    status: "keep",
    title: "Shipwreck in Haven, Part Four",
    url: "http://www.poetryfoundation.org/poem/238362",
  },
  {
    author: " Alfred,Lord Tennyson ",
    id: 0.08522639956672806,
    line1: " i said to the rose,",
    line2: " the brief night goes in babble ",
    line3: " and revel and wine.",
    status: "keep",
    title: " Maud(Part I)",
    url: " http: //www.poetryfoundation.org/poem/174634",
  },
  {
    author: "Molly Peacock",
    id: 0.8664274364592235,
    line1: " like a small poem",
    line2: " on a long scroll, a lily pad",
    line3: " appeared on the pond.",
    status: "keep",
    title: "The Poet",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/249134",
  },
  {
    author: "Mary Ruefle",
    id: 0.8742080167495907,
    line1: " as quietly as",
    line2: " the sound of kleenex being pulled",
    line3: " from a box, i sneezed.",
    status: "keep",
    title: "Shalimar",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/242472",
  },
  {
    author: "Arthur Sze",
    id: 0.09232894307786466,
    line1: " you do not need to",
    line2: " steep turtle shells in blood to",
    line3: " prognosticate clouds.",
    status: "keep",
    title: "Chrysalis",
    url: "http://www.poetryfoundation.org/poem/182197",
  },
  {
    author: "Louise Bogan",
    id: 0.5969150217934093,
    line1: " she has attained the",
    line2: " permanence she dreamed of, where",
    line3: " old stones lie sunning.",
    status: "keep",
    title: "Epitaph for a Romantic Woman",
    url: "http://www.poetryfoundation.org/poem/172945",
  },
  {
    author: "John Frederick Nims",
    id: 0.842822688802684,
    line1: " fine coral as the shy",
    line2: " and wild tonguetip, undersea coral,",
    line3: " rich as inner lip.",
    status: "keep",
    title: "Decline and Fall",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/15593",
  },
  {
    author: "Robert Hass",
    id: 0.977835455679387,
    line1: " the blackbirds settled",
    line2: " their clannish squabbles in the",
    line3: " reeds, and light came up.",
    status: "keep",
    title: "Between the Wars",
    url: "http://www.poetryfoundation.org/poem/179748",
  },
  {
    author: "G. K. Chesterton",
    id: 0.42436471496218686,
    line1: " the brown bird stirred in",
    line2: " the dead man's hair and it seemed",
    line3: " that the dead man stirred.",
    status: "keep",
    title: "The Ballad of God-Makers",
    url: "http://www.poetryfoundation.org/poem/177443",
  },
  {
    author: "David Bottoms",
    id: 0.8957144610128382,
    line1: " the black leaves shined, the",
    line2: " pink fruit blossomed red, ugly",
    line3: " as a human heart.",
    status: "keep",
    title: "Under the Vulture-Tree",
    url: "http://www.poetryfoundation.org/poem/175602",
  },
  {
    author: "Carl Sandburg",
    id: 0.983275490970672,
    line1: " shovel them under",
    line2: " and let me work--- i am the",
    line3: " grass; i cover all.",
    status: "keep",
    title: "Grass",
    url: "http://www.poetryfoundation.org/poem/174301",
  },
  {
    author: "Forrest Gander",
    id: 0.9015620824067927,
    line1: " above the river, heat",
    line2: " lightning flicks silently and the",
    line3: " sound holds, coiled in air.",
    status: "keep",
    title: "The Moment When Your Name is Pronounced",
    url: "http://www.poetryfoundation.org/poem/176267",
  },
  {
    author: "Yusef Komunyakaa",
    id: 0.3508468278706123,
    line1: " the distant night opens",
    line2: " like a pearl fan, a skirt, a",
    line3: " heart, a drop of salt.",
    status: "keep",
    title: "Confluence",
    url: "http://www.poetryfoundation.org/poem/177462",
  },
  {
    author: "Robert Hass",
    id: 0.8574888586978635,
    line1: " outside, the day is",
    line2: " slowly succeeded by night,",
    line3: " succeeded by day.",
    status: "keep",
    title: "Misery and Splendor",
    url: "http://www.poetryfoundation.org/poem/179749",
  },
  {
    author: "Edwin Markham",
    id: 0.40233404659532535,
    line1: " what carols, like the",
    line2: " blazon of a king, fill all",
    line3: " the dawn with wonder?",
    status: "keep",
    title: "A Lyric of the Dawn",
    url: "http://www.poetryfoundation.org/poem/177472",
  },
  {
    author: "John Logan",
    id: 0.09821293401381737,
    line1: " for lunch i bit the",
    line2: " olive meat: a yellow jacket",
    line3: " stung me on the tongue.",
    status: "keep",
    title: "Shore Scene",
    url: "http://www.poetryfoundation.org/poem/177552",
  },
  {
    author: "Derek Walcott",
    id: 0.24241484124230206,
    line1: " a mongoose charges dry",
    line2: " grass and fades through a fence faster",
    line3: " than an afterthought.",
    status: "keep",
    title: "Becune Point",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/29636",
  },
  {
    author: "Jane Kenyon",
    id: 0.4010676124829812,
    line1: " the stone trough was still",
    line2: " filled with water: she watched it",
    line3: " and received its calm.",
    status: "keep",
    title: "Portrait of a Figure near Water",
    url: "http://www.poetryfoundation.org/poem/175709",
  },
  {
    author: "John Engels",
    id: 0.9573539866342184,
    line1: " when the trout dies it",
    line2: " turns its white belly to the",
    line3: " mirror of the sky.",
    status: "keep",
    title: "Damselfly, Trout, Heron",
    url: "http://www.poetryfoundation.org/poem/177648",
  },
  {
    author: "Bruce Snider",
    id: 0.26102272567047413,
    line1: " i wake to leafless",
    line2: " vines and muddy fields, patches",
    line3: " of standing water.",
    status: "keep",
    title: "Afterlife",
    url: "http://www.poetryfoundation.org/poem/246112",
  },
  {
    author: "David Wojahn",
    id: 0.4783817749595619,
    line1: " january, vermont:",
    line2: " snowflakes teased the windows of the",
    line3: " burlington airport bar.",
    status: "keep",
    title: "Scrabble with Matthews",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/30900",
  },
  {
    author: "Joy Harjo",
    id: 0.7757936957184479,
    line1: " my granddaughter sleeps",
    line2: " on the breast of her mother",
    line3: " with milk on her mouth.",
    status: "keep",
    title: "Insomnia and the Seven Steps to Grace",
    url: "http://www.poetryfoundation.org/poem/177196",
  },
  {
    author: "Mary Karr",
    id: 0.37798170060804437,
    line1: " when my plane tilts down,",
    line2: " houses grow large, streets lose their",
    line3: " clear geometry.",
    status: "keep",
    title: "Limbo Altered States",
    url: "http://www.poetryfoundation.org/poem/171887",
  },
  {
    author: "Anne Carson",
    id: 0.1804835739374835,
    line1: " on the edge of the",
    line2: " moor our pines dip and coast in",
    line3: " breezes from somewhere else.",
    status: "keep",
    title: "The Glass Essay",
    url: "http://www.poetryfoundation.org/poem/178364",
  },
  {
    author: "Cesare Pavese",
    id: 0.9705640517793921,
    line1: " outside my door, the",
    line2: " quiet roads lead, after a",
    line3: " short walk, to open fields.",
    status: "keep",
    title: "Passion for Solitude",
    url: "http://www.poetryfoundation.org/poem/180248",
  },
  {
    author: "Emily Rosko",
    id: 0.6185091081793768,
    line1: " you said, this place should",
    line2: " be more festive: a lightning",
    line3: " bolt, a snail, a fraud.",
    status: "keep",
    title: "Prop Rockery",
    url: "http://www.poetryfoundation.org/poem/249730",
  },
  {
    author: "Vera Pavlova",
    id: 0.24673430161492327,
    line1: " only they who have",
    line2: " been breast-fed know the beauty",
    line3: " of the clavicle.",
    status: "keep",
    title: "Only she who has breast-fed",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/238390",
  },
  {
    author: "Debora Greger",
    id: 0.28405310291852004,
    line1: " you peck at a slug",
    line2: " sliming your path, seeming to",
    line3: " beg your forgiveness.",
    status: "keep",
    title: "Les Tres Riches Heures de Florida",
    url: "http://www.poetryfoundation.org/poem/176409",
  },
  {
    author: "Abigail Deutsch",
    id: 0.1758007500857477,
    line1: " my students grew hair",
    line2: " and got haircuts, grew hair and",
    line3: " got haircuts, and sang.",
    status: "keep",
    title: "Twenty-Two",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/250090",
  },
  {
    author: "Matthew Nienow",
    id: 0.39202332537231455,
    line1: " a sea gull beaks a",
    line2: " crab, flights vertically and",
    line3: " drops it to the rocks.",
    status: "keep",
    title: "Bad Year Anthem",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/246712",
  },
  {
    author: "James Longenbach",
    id: 0.8507793760845968,
    line1: " why, since the forest",
    line2: " is beautiful, is it not",
    line3: " a place of delight?",
    status: "keep",
    title: "Allegory",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/246022",
  },
  {
    author: "Dean Young",
    id: 0.3837764877747658,
    line1: " your dead cat loves you",
    line2: " forever and will welcome",
    line3: " you forever home.",
    status: "keep",
    title: "The New Optimism",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/240244",
  },
  {
    author: "Paul Muldoon",
    id: 0.3012362951144033,
    line1: " every ass had an",
    line2: " ass's jawbone that might itself",
    line3: " drop from grin to girn.",
    status: "keep",
    title: "The Old Country",
    url: "http://www.poetryfoundation.org/poem/246550",
  },
  {
    author: "Dean Young",
    id: 0.4531379349207829,
    line1: " that dusty bubble gum,",
    line2: " once ubiquitous as starlings,",
    line3: " is no more, my love.",
    status: "keep",
    title: "Bronzed",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/26",
  },
  {
    author: "Joy Harjo",
    id: 0.03234310038445187,
    line1: " ah, ah cries the crow",
    line2: " arching toward the heavy sky",
    line3: " over the marina.",
    status: "keep",
    title: "Ah, Ah",
    url: "http://www.poetryfoundation.org/poem/179780",
  },
  {
    author: "Joanne Kyger",
    id: 0.02866181825047709,
    line1: " as the pieces of the",
    line2: " house ooze sap, blossoms and green",
    line3: " twigs burst from the cracks.",
    status: "keep",
    title: "The Test of Fantasy",
    url: "http://www.poetryfoundation.org/poem/242594",
  },
  {
    author: "D. H. Lawrence",
    id: 0.9202161068825683,
    line1: " wings and feathers on",
    line2: " the crying, mysterious",
    line3: " ages, peewits wheeling!",
    status: "keep",
    title: "The Wild Common",
    url: "http://www.poetryfoundation.org/poem/173847",
  },
  {
    author: "A. V. Christie",
    id: 0.9654896822278799,
    line1: " grubs are larger than",
    line2: " pale yellow larvae i prize",
    line3: " from inside chestnuts.",
    status: "keep",
    title: "The Hen Swallows a Worm or Slug",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/237712",
  },
  {
    author: "Dara Wier",
    id: 0.7137559890096385,
    line1: " the rifle's blue-black",
    line2: " barrel shone in the corner",
    line3: " against the white, white wall.",
    status: "keep",
    title: "Little Black Tangrams",
    url: "http://www.poetryfoundation.org/poem/181830",
  },
  {
    author: "Lisa Olstein",
    id: 0.7789938428594791,
    line1: " yours is the name the",
    line2: " leaves chatter at the edge of",
    line3: " the unrabbited woods.",
    status: "keep",
    title: "Dear One Absent This Long While",
    url: "http://www.poetryfoundation.org/poem/177696",
  },
  {
    author: "Jane Cooper",
    id: 0.8999606126399657,
    line1: " the last full moon of",
    line2: " february stalks the fields; barbed",
    line3: " wire casts a shadow.",
    status: "keep",
    title: "Hunger Moon",
    url: "http://www.poetryfoundation.org/poem/242454",
  },
  {
    author: "Anthony Madrid",
    id: 0.706209297438384,
    line1: " i like the shape of",
    line2: " the pouring soy milk, the sound",
    line3: " of the splitting log.",
    status: "keep",
    title: "Once upon a Time",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/243776",
  },

  {
    author: "George Seferis",
    id: 0.8370403399378663,
    line1: " the light was fading",
    line2: " from the clouded day, no one",
    line3: " decided anything.",
    status: "keep",
    title: "The Last Day",
    url: "http://www.poetryfoundation.org/poem/181848",
  },
  {
    author: "Emily Pauline Johnson",
    id: 0.6475761399330323,
    line1: " among the wild rice in",
    line2: " the still lagoon, in monotone",
    line3: " the lizard shrills his tune.",
    status: "keep",
    title: "Marshlands",
    url: "http://www.poetryfoundation.org/poem/182757",
  },
  {
    author: "Nate Klug",
    id: 0.9800631046609507,
    line1: " nights, a tin roof wind",
    line2: " cracked flat; my sister, flushed with",
    line3: " child, hushing a child.",
    status: "keep",
    title: "Kalden's Story",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/179998",
  },
  {
    author: "Mary Mapes Dodge",
    id: 0.11719460390077607,
    line1: " i am hungry and",
    line2: " cold, and last night i dreamed a",
    line3: " scarecrow had caught me",
    status: "keep",
    title: "Poor Crow!",
    url: "http://www.poetryfoundation.org/poem/182729",
  },
  {
    author: "David Baker",
    id: 0.2973605463500517,
    line1: " how like a field is",
    line2: " the whole sky now that the maples",
    line3: " have shed their leaves, too.",
    status: "keep",
    title: "Neighbors in October",
    url: "http://www.poetryfoundation.org/poem/171089",
  },
  {
    author: "Anthony Madrid",
    id: 0.49480359995254974,
    line1: " which of you knows how",
    line2: " to part the pebble on the",
    line3: " beach from its colors?",
    status: "keep",
    title: "Like a Cloud above a Ravine",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/246868",
  },
  {
    author: "William Meredith",
    id: 0.14095961249150069,
    line1: " forsythia and lilac",
    line2: " have overgrown the porch, there is",
    line3: " the rich smell of wood-rot.",
    status: "keep",
    title: "Politics",
    url: "http://www.poetryfoundation.org/poem/171859",
  },

  {
    author: "Chris Abani",
    id: 0.7472798184461072,
    line1: " the world is old, the",
    line2: " world is new the sun is no",
    line3: " bigger than a crab.",
    status: "keep",
    title: "Chant:",
    url: "http://www.poetryfoundation.org/poem/237402",
  },
  {
    author: "Alfred Corn",
    id: 0.3411673454321895,
    line1: " the waiting cattle",
    line2: " stir and low as daylight breaks",
    line3: " in on the darkness.",
    status: "keep",
    title: "An Xmas Murder",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/26213",
  },
  {
    author: "John Ashbery",
    id: 0.906494030940811,
    line1: " his dear one, his wife,",
    line2: " is young and pretty; her shawl",
    line3: " is rose, pink, and white.",
    status: "keep",
    title: "The Instruction Manual",
    url: "http://www.poetryfoundation.org/poem/177261",
  },
  {
    author: "Nick Lantz",
    id: 0.6780288353176026,
    line1: " his family dropped",
    line2: " away like cicada husks swept",
    line3: " off tree trunks by rain.",
    status: "keep",
    title: "Either Or",
    url: "http://www.poetryfoundation.org/poem/240424",
  },
  {
    author: "Amy Lowell",
    id: 0.47663653803122974,
    line1: " a drunken moon ogling",
    line2: " a sycamore, running long fingers",
    line3: " down its shining flank.",
    status: "keep",
    title: "Nuit Blanche",
    url: "http://www.poetryfoundation.org/poem/171718",
  },
  {
    author: "Brenda Cárdenas",
    id: 0.14642435682474608,
    line1: " your back, a blue-black",
    line2: " silhouette, feet wet with the",
    line3: " wash of morning waves.",
    status: "keep",
    title: "Song",
    url: "http://www.poetryfoundation.org/poem/185637",
  },
  {
    author: "James Schuyler",
    id: 0.16302998614781994,
    line1: " under lilacs unleaved",
    line2: " lie a clump of snowdrops and",
    line3: " one purple crocus.",
    status: "keep",
    title: "Hymn to Life",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/21778",
  },
  {
    author: "R. T. Smith",
    id: 0.7364347251452751,
    line1: " the moon was new in",
    line2: " the budding bird cherry and",
    line3: " venus startling overhead.",
    status: "keep",
    title: "Messenger",
    url: "http://www.poetryfoundation.org/poem/176373",
  },
  {
    author: "Joseph Brodsky",
    id: 0.5500235183066433,
    line1: " here are your cicadas,",
    line2: " then a chickadee, the bulb's dry",
    line3: " tear in your lemon tea.",
    status: "keep",
    title: "Song of Welcome",
    url: "http://www.poetryfoundation.org/poem/249972",
  },
  {
    author: "Francis Ledwidge",
    id: 0.22618275929994414,
    line1: " it was too early",
    line2: " for the lark, but the starry",
    line3: " dark had tints of gold.",
    status: "keep",
    title: "The Dead Kings",
    url: "http://www.poetryfoundation.org/poem/248546",
  },
  {
    author: "Martha Ronk",
    id: 0.5104749989580365,
    line1: " one remembers rain",
    line2: " even in its absence and an",
    line3: " attendant quiet.",
    status: "keep",
    title: "In a landscape of having to repeat",
    url: "http://www.poetryfoundation.org/poem/179266",
  },
  {
    author: "Norman Dubie",
    id: 0.22499981129973812,
    line1: " the anxious pianist",
    line2: " eats the edges of a fig stuffed",
    line3: " with devonshire cream.",
    status: "keep",
    title: "The Composer's Winter Dream",
    url: "http://www.poetryfoundation.org/poem/181854",
  },
  {
    author: "James Galvin",
    id: 0.9285373359973259,
    line1: " the pole bean tendrils",
    line2: " sought their frames within six hours",
    line3: " of my setting them.",
    status: "keep",
    title: "Stories Are Made of Mistakes",
    url: "http://www.poetryfoundation.org/poem/181571",
  },
  {
    author: "Frederick Seidel",
    id: 0.7966304047329115,
    line1: " the dying leaves are",
    line2: " sizzling on the trees in a",
    line3: " shirtsleeves summer breeze.",
    status: "keep",
    title: "What Next",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/244430",
  },
  {
    author: "Sara Littlecrow-Russell",
    id: 0.9801099333247295,
    line1: " you are the love song",
    line2: " played on a reedless flute that",
    line3: " only spirits hear.",
    status: "keep",
    title: "Song from a Reedless Flute",
    url: "http://www.poetryfoundation.org/poem/239034",
  },
  {
    author: "Seamus Heaney",
    id: 0.2896761808821605,
    line1: " was there not a line",
    line2: " of turnips where the seed ran out",
    line3: " in the potato field?",
    status: "keep",
    title: "Singing School",
    url: "http://www.poetryfoundation.org/poem/178022",
  },
  {
    author: "James McMichael",
    id: 0.568441999109621,
    line1: " cows grazed the catchwork",
    line2: " meadows on the terraces, or",
    line3: " at the watersides.",
    status: "keep",
    title: "Four Good Things",
    url: "http://www.poetryfoundation.org/poem/175890",
  },
  {
    author: "David Wojahn",
    id: 0.012163505361609928,
    line1: " dawnlight, everything",
    line2: " dripping wet, and the chairs stare",
    line3: " at each other, alone.",
    status: "keep",
    title: "Ghost Supper",
    url: "http://www.poetryfoundation.org/poem/177329",
  },
  {
    author: "Ben Belitt",
    id: 0.5306985683161118,
    line1: " in the distance the",
    line2: " litter-bearers are leaning",
    line3: " for the litter-poles.",
    status: "keep",
    title: "The Spool",
    url: "http://www.poetryfoundation.org/poem/178203",
  },
  {
    author: "Lizette Woodworth Reese",
    id: 0.5215642441534373,
    line1: " from out the hedge the",
    line2: " wind lets fall a few last flakes,",
    line3: " ragged and delicate.",
    status: "keep",
    title: "Mid-March",
    url: "http://www.poetryfoundation.org/poem/182748",
  },

  {
    author: "Katharine Coles",
    id: 0.22241195794488566,
    line1: " over the water the",
    line2: " shags come in to land all wings,",
    line3: " uh-ohing over the cliffs.",
    status: "keep",
    title: "Tempo for a Winged Instrument",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/244214",
  },
  {
    author: "Reginald Gibbons",
    id: 0.9440978346089064,
    line1: " the new wire of the",
    line2: " telephone, dozing in a coil,",
    line3: " waits for the first call.",
    status: "keep",
    title: "Luckies",
    url: "http://www.poetryfoundation.org/poem/176274",
  },
  {
    author: "Philip Levine",
    id: 0.22520756096190786,
    line1: " a vision comes to",
    line2: " an ordinary man staring",
    line3: " at a filthy river.",
    status: "keep",
    title: "On the Meeting of Garcia Lorca and Hart Crane",
    url: "http://www.poetryfoundation.org/poem/182874",
  },
  {
    author: "Carl Rakosi",
    id: 0.519160697436467,
    line1: " what can be compared",
    line2: " to light in which leaves darken",
    line3: " after rain, fierce green?",
    status: "keep",
    title: "Associations with a View from the House",
    url: "http://www.poetryfoundation.org/poem/176504",
  },
  {
    author: "Khaled Mattawa",
    id: 0.07564601514570368,
    line1: " in the dark the eyes",
    line2: " of startled creatures gleam like",
    line3: " a herd of candles.",
    status: "keep",
    title: "Bedtime Reading for the Unborn Child",
    url: "http://www.poetryfoundation.org/poem/240906",
  },
  {
    author: "Charles Wright",
    id: 0.20170933372487954,
    line1: " after a day of",
    line2: " high winds, how beautiful is",
    line3: " the stillness of dusk.",
    status: "keep",
    title: "Nine-Panel Yaak River Screen",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/30439",
  },
  {
    author: "Gary Soto",
    id: 0.7825398845581091,
    line1: " i patted my hair",
    line2: " when i entered the wind of",
    line3: " a revolving door.",
    status: "keep",
    title: "Self-Inquiry Before the Job Interview",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/30461",
  },
  {
    author: "Walt Whitman",
    id: 0.4546614078947019,
    line1: " clear and sweet is my",
    line2: " soul, and clear and sweet is all",
    line3: " that is not my soul.",
    status: "keep",
    title: "Song of Myself (1892 version)",
    url: "http://www.poetryfoundation.org/poem/174745",
  },
  {
    author: "Ted Kooser",
    id: 0.9383834865962999,
    line1: " blue morning glories",
    line2: " climb halfway up the stairs, bright",
    line3: " clusters of laughter.",
    status: "keep",
    title: "The Giant Slide",
    url: "http://www.poetryfoundation.org/poem/171345",
  },
  {
    author: "Justin Chin",
    id: 0.8297165146420049,
    line1: " the channel changer",
    line2: " is lost in the crack of an",
    line3: " infinite sofa.",
    status: "keep",
    title: "Grave",
    url: "http://www.poetryfoundation.org/poem/241450",
  },
  {
    author: "Paisley Rekdal",
    id: 0.7077086045435035,
    line1: " i can stand for hours",
    line2: " among the sweet narcissus, silent",
    line3: " as a point of bone.",
    status: "keep",
    title: "Happiness",
    url: "http://www.poetryfoundation.org/poem/245910",
  },
  {
    author: "Ofelia Zepeda",
    id: 0.6598415752150291,
    line1: " every now and then",
    line2: " with the back of his gloved hand",
    line3: " he wipes the windshield.",
    status: "keep",
    title: "The Place Where Clouds Are Formed",
    url: "http://www.poetryfoundation.org/poem/239010",
  },
  {
    author: "A. F. Moritz",
    id: 0.9890262280167084,
    line1: " the streets crack, a house",
    line2: " falls open to the air, sun and",
    line3: " rain lie on the bed.",
    status: "keep",
    title: "Lost Content",
    url: "http://www.poetryfoundation.org/poem/175444",
  },
  {
    author: "Matthew Arnold",
    id: 0.18152237672568328,
    line1: " who imagines her fields",
    line2: " as they lay in the sunshine,",
    line3: " unworn by the plough?",
    status: "keep",
    title: "The Future",
    url: "http://www.poetryfoundation.org/poem/172846",
  },
  {
    author: "Marilyn Hacker",
    id: 0.15705776731277343,
    line1: " now i walk home along",
    line2: " the river, into the wind,",
    line3: " as the clouds break open.",
    status: "keep",
    title: "Days of 1994: Alexandrians",
    url: "http://www.poetryfoundation.org/poem/176234",
  },
  {
    author: "Edgar Bowers",
    id: 0.7637686578128158,
    line1: " with their harsh leaves old",
    line2: " rhododendrons fill the crevices in",
    line3: " grave plots' broken stones.",
    status: "keep",
    title: "The Mountain Cemetery",
    url: "http://www.poetryfoundation.org/poem/171962",
  },
  {
    author: "Mary Ruefle",
    id: 0.7862234824777525,
    line1: " they sweep the sand from",
    line2: " the shore, feet standing in neat",
    line3: " little rows of foam.",
    status: "keep",
    title: "The Wife of Mission Rock",
    url: "http://www.poetryfoundation.org/poem/238534",
  },
  {
    author: "Mark Doty",
    id: 0.9159677861771408,
    line1: " husk, leaf, little boat",
    line2: " of paper and wood to mark",
    line3: " the speed of the stream?",
    status: "keep",
    title: "Atlantis",
    url: "http://www.poetryfoundation.org/poem/178815",
  },
  {
    author: "Chungmi Kim",
    id: 0.7954502579668343,
    line1: " cockroaches are my",
    line2: " temporary friends dwelling in their",
    line3: " underground castles.",
    status: "keep",
    title: "My Sin",
    url: "http://www.poetryfoundation.org/poem/237580",
  },
  {
    author: "Rigoberto González",
    id: 0.8360059038814963,
    line1: " off with you, old couch",
    line2: " that cries in coins as it gets",
    line3: " dragged out to the porch.",
    status: "keep",
    title: "Casa",
    url: "http://www.poetryfoundation.org/poem/249808",
  },
  {
    author: "Rynn Williams",
    id: 0.9563281588492349,
    line1: " there is a piece of",
    line2: " gum beneath the windowsill, green",
    line3: " imprint of a thumb.",
    status: "keep",
    title: "Positive",
    url: "http://www.poetryfoundation.org/poem/238554",
  },
  {
    author: "Joseph Brodsky",
    id: 0.42767148205867955,
    line1: " a ray of the moon,",
    line2: " meanwhile, draws up the tide like",
    line3: " a slipping blanket.",
    status: "keep",
    title: "A Part of Speech",
    url: "http://www.poetryfoundation.org/poem/249960",
  },
  {
    author: "Allison Adelle Hedge Coke",
    id: 0.05268860607212211,
    line1: " silver maple samaras",
    line2: " wing wind, spread clusters along with",
    line3: " mine, renewing prairie.",
    status: "keep",
    title: "Redwing Blackbird",
    url: "http://www.poetryfoundation.org/poem/240126",
  },
  {
    author: "Thomas McGrath",
    id: 0.3231425206817047,
    line1: " did the sun shake down",
    line2: " a million bells and birds bloom",
    line3: " on bough in wildest song!",
    status: "keep",
    title: "Celebration for June 24",
    url: "http://www.poetryfoundation.org/poetrymagazine/poem/13059",
  },
  {
    author: "Percy Bysshe Shelley",
    id: 0.07802673776719482,
    line1: " the oak, expanding",
    line2: " its immense and knotty arms,",
    line3: " embraces the light beech.",
    status: "keep",
    title: "Alastor; or, The Spirit of Solitude",
    url: "http://www.poetryfoundation.org/poem/174380",
  },
  {
    author: "Mother Goose",
    id: 0.11042879994384547,
    line1: " they began to sigh,",
    line2: "meow, meow, meow, then",
    line3: " they began to sigh.",
    status: "keep",
    title: "The three little kittens, they lost their mittens,",
    url: "http://www.poetryfoundation.org/poem/176347",
  },
  {
    author: "Sean Nevin",
    id: 0.08293244501837327,
    line1: " they emerge from cocoons",
    line2: " like greased hinges, all pheromone and wing,",
    line3: " instinct and flutter.",
    status: "keep",
    title: "Hinged Double Sonnet for the Luna Moths",
    url: "http://www.poetryfoundation.org/poem/182333",
  },
  {
    author: "Kenneth Rexroth",
    id: 0.9836475591879085,
    line1: " our campfire is a",
    line2: " single light amongst a hundred",
    line3: " peaks and waterfalls.",
    status: "keep",
    title: "The Wheel Revolves",
    url: "http://www.poetryfoundation.org/poem/171529",
  },
  {
    author: "Anya Silver",
    id: 0.4468406436778253,
    line1: " the wind tongues me to",
    line2: " my feet like a doe licking",
    line3: " clean her newborn fawn.",
    status: "keep",
    title: "Leaving the Hospital",
    url: "http://www.poetryfoundation.org/poem/243474",
  },
  {
    author: "Curzio Malaparte",
    id: 0.48052993286923795,
    line1: " the rain on the oak",
    line2: " leaves made a soft music, like",
    line3: " women whispering.",
    status: "keep",
    title: "Murderer [Part I]",
    url: "http://www.poetryfoundation.org/poem/245718",
  },
  {
    author: "Amy Lowell",
    id: 0.17219689715510655,
    line1: " the sky is quiet",
    line2: " and high, and the morning is",
    line3: " fair with fresh-washed air.",
    status: "keep",
    title: "Spring Day",
    url: "http://www.poetryfoundation.org/poem/239802",
  },
  {
    author: "B. H. Fairchild",
    id: 0.17331649464547993,
    line1: " the nurses waved, white",
    line2: " dresses puffed out like pigeons",
    line3: " in the morning breeze.",
    status: "keep",
    title: "Angels",
    url: "http://www.poetryfoundation.org/poem/176018",
  },
  {
    author: "Tishani Doshi",
    id: 0.049203683713000435,
    line1: " this murmur in the",
    line2: " mouth of the mountain where the",
    line3: " sound of rain is born.",
    status: "keep",
    title: "The River of Girls",
    url: "http://www.poetryfoundation.org/poem/247092",
  },
];
